### PR TITLE
Implement drivers (AppStream)

### LINKED ISSUE #12: A sane place for Additional Drivers [$125]
There was a question about this : https://answers.launchpad.net/elementaryos/+question/268252
The answer is correct but confusing for users who need this tool.

As requested  i would make a blueprint but a bug seems more logical now.
because the feature is there only not on the place people would suspect.

Launchpad Details: [#LP1469733](https://bugs.launchpad.net/bugs/1469733) kay van der Zander - 2015-06-29 14:05:02 +0000

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/43123426-a-sane-place-for-additional-drivers?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by donadigo**
Implements drivers and fixes #12.

After discussion on the Slack channel I decided to give AppStream implementation of drivers a go. We no longer depend on any Ubuntu / Debian specific code. Everything is based on AppStream and PackageKit, however scanning modaliases on the system is pretty much a Vala version of the UbuntuDrivers component. For more details about the code and it's design, look into the diff, I left some explanation for each driver related method.

Note that currently there is no AppStream data to test this branch with and this is kind of a problem since this feature is being asked by lots of people. So how did I test it?
The way to test this is to fool AppStream that some components are drivers. All of the compiled data is stored in `/usr/share/app-info/yaml/pantheon_xenial-main_amd64.yml.gz` file. Open this file with archive manager (with admin), and edit the .yml file inside of it. Choose some component and change it's `Type` field from `desktop-app` to `driver`. Next you will need a supported modalias by your system. These can be found by e.g: executing `ubuntu-drivers debug` and choosing one of the `modalias` strings. After that you can paste this under the `Provides` field:
```
modaliases:
  - your_modalias
```

and save the file.

Sorry if this is really complicated but this is the only way I found to test this. Perhaps Matthias knows a better way.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@donadigo Is there a way we could have both backends supported, and have a build-time option to use one or the other?

**Comment by donadigo** [comment]
@Conan-Kudo yes, we could use conditional compiling here.

**Comment by Philip-Scott** [comment]
Is this PR still valid? Or does your other PR for the drivers supersede this?

**Comment by decathorpe** [comment]
Could you rebase this against current master?
I think this change would make driver support work on fedora, too, since drivers already work with gnome-software / packagekit / appstream.

**Comment by jeremypw** [comment]
@donadigo Converting to draft as has conflicts and no recent activity. Please feel free to close or request review as desired.

**Pull request closed without merging**
