### PR TITLE
Add new build variables for downstreams

### PR DESCRIPTION
**Pull request by codygarver**
Add new build variables for downstreams:
 * DEFAULT_BANNER_COLOR_PRIMARY
 * DEFAULT_BANNER_COLOR_PRIMARY_TEXT
 * INSTALL_BUTTON_LABEL

### CODE REVIEW

**Comment by codygarver** [comment]
Just a couple of simple `Pop!_Shop` changes I noticed could be upstreamed.

**Comment by codygarver** [comment]
Need to add "Free" to translation template and this will be good to go.

**Comment by codygarver** [comment]
Ready for review.

**Comment by danrabbit** [comment]
Closing because AppCenter uses Meson now so if these options are still needed we'll want to port them to Meson

**Pull request closed without merging**
