### PR TITLE
Content ratings

### LINKED ISSUE #34: Expose content rating
Currently GNOME Software is using https://odrs.gnome.org/oars
It seems to provide a wide range of granularity but more is better than less here

It would be nice to expose it to the user.

~A nice to have would be to be able to restrict certain categories in the Parental Control Plug~ See #629 

Launchpad Details: [#LP1665076](https://bugs.launchpad.net/bugs/1665076) Corentin Noël - 2017-02-15 18:55:59 +0000

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/43123507-expose-content-rating?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cassidyjames**
WIP (just a nonfunctional prototype for now). Will fix #34. We should get some nice icons as mentioned in #34. Design input _very_ welcome. :D

image 17

### CODE REVIEW

**Comment by danrabbit** [comment]
I feel like content ratings should be maybe at the top of the listing instead of the bottom to make sure that users see them. For comparison, in the mac app store they show the age rating right below the install button: https://media.idownloadblog.com/wp-content/uploads/2018/09/adware-doctor.jpg

**Comment by snowparrot** [comment]
you can watch at https://en.wikipedia.org/wiki/Pan_European_Game_Information

Im still sceptical as some pictograms are highly depend what is a taboo in society. 

We can take "Sex & Nudity" in Germany and America as an example. Non-Sexual nudity isnt a taboo in Germany. (here https://en.wikipedia.org/wiki/Freik%C3%B6rperkultur ) while in America it is a highly taboo. (There is also a growing anger about Facebook's female nipple policy in Germany as it is seen as paternalism.) Part of this cultural divergence the PEGI symbols have just a symbol for sexual content not nudity! So if you just use a sexual symbol in the pictogram it doesnt have the exact meaning of the rating. Otherwise if you include nudity it can be seen as paternalism in other ones. 
My example emphasises what even closed-linked Western cultures do have strong differences that pictogramms must reflect. 

Other obvious example are "illicit substances" which excludes alcohol for many countries but not for all. (e.g. Saudi-Arabia).

**Comment by snowparrot** [comment]
I am still not satisfied with the symbols of the PEGI as the sexual content pictogram excludes gay content (which might be a stronger taboo in many countries.)

**Comment by jeremypw** [comment]
@cassidyjames: Converting to draft as has conflicts and/or no recent activity.  Please feel free to close or reopen for review after fixing conflicts as desired.

**Pull request closed without merging**
