### PR TITLE
Create is_native in Package.vala and use in AppListView.vala

### PR DESCRIPTION
**Pull request by danrabbit**
Save some lines and kill the animals

### CODE REVIEW

**Comment by donadigo** [comment]
Instead of having that function in `AppListView`, you should make it a part of the `Package` itself.

**Comment by davidmhewitt** [comment]
I'd be tempted to keep the origin strings as consts at the top of the file just so they're big capital letters and easy to spot when we come to change the repo names.

**Comment by donadigo** [comment]
@davidmhewitt made a good point. I'll approve this after his requested change.

**Comment by donadigo** [comment]
Looking good now! :)

**Pull request merged**
