### PR TITLE
Show loading placeholder unless no results returned

### LINKED ISSUE #975: Inappropriate message when Installed View first shown
* Open AppCenter
* Click "Installed" button
* The view opens with the message " No Results. No Apps could be found. Try changing search terms" 

This message persists while the "working" spinner is active, which may be for several seconds, before the actual list of installed apps is shown.

While the spinner is active, either no message or a more appropriate message should be shown.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72399005-inappropriate-message-when-installed-view-first-shown?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #975 

Needs design input on icon and wording of the loading placeholder.

### CODE REVIEW

**Comment by jeremypw** [comment]
Temporary loading placeholder AlertView.
Screenshot from 2020-04-10 18 28 17

**Comment by danrabbit** [comment]
Looks like according to the spec that `sync-synchronizing` is probably the best icon name: https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

Proposed a branch here to add our own icons for that: https://github.com/elementary/icons/pull/879

**Comment by danrabbit** [comment]
Maybe something like:

Screenshot from 2020-04-10 11 21 33@2x

I'm not sure if "package" is considered jargon here. @cassidyjames thoughts?

**Comment by cassidyjames** [comment]
@danrabbit I think “Checking for Updates” as the header would be fine, even if that's not all it's doing—it's probably the most relevant and understandable bit.

Maybe something like:

>**Checking for Updates**
>Verifying installed apps plus checking updates to the OS and apps.

Still feels a little stilted. But "packages" does seem really jargony to me.

**Comment by jeremypw** [comment]
@cassidy I am not sure "Verifying installed apps" is very meaningful to the average user.  How about "Checking for updates to the OS and installed apps"?

**Comment by jeremypw** [comment]
I was concerned that the loading_view might appear during searching in which case the text would not be appropriate, but in fact, the the search view only appears after the search is complete so this is not a concern.  Have amended text and icon as per suggestions from UX team.

**Comment by jeremypw** [comment]
Since merging master, this no longer works as expected - the installed view is populated immediately while checking for updates is ongoing.  Do we still need a message? If so where should it appear InfoBar?

**Pull request merged**
