### PR TITLE
Don't show share popover for OS updates

### LINKED ISSUE #368: OS updates should not be shareable
You should not be able to share "OS updates"

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #368

### CODE REVIEW

**Comment by codygarver** [comment]
Maybe Operating System Updates shouldn't have a page at all.

**Comment by cassidyjames** [comment]
@codygarver I think we do want it as a potential place for a changelog, though.

**Comment by tintou** [comment]
@cassidyjames that would be a lot of various changelogs.

**Comment by donadigo** [comment]
I think what you should do here perhaps is to have a `can_share` method in the `Package` class and call that instead of throwing that statement there.  One thing that I also thought is that sharing drivers also currently doesn't work.

**Comment by jeremypw** [comment]
If "shareability" is more complex than whether or not a package is an os-update then I agree with donadigo that this should be handled within Package and exposed as a single property.

**Comment by ramirocantu** [comment]
Should drivers have a sharing link?

**Pull request merged**
