### PR TITLE
AppInfoView: Show an icon for uncurated apps

### LINKED ISSUE #233: Expose non-curated app remote
I've heard from a couple folks that they want a way to know which apps were made for elementary OS. While we still have apps from the Ubuntu repos, perhaps we need a way to mark those apps so that people know that they are not from our repos.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44000145-mark-apps-from-the-ubuntu-repos?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #233

Pretty wordy. I also wonder if we could come up with a better title than "Not Reviewed" but more obviously meaningful than just "Non-curated" which I feel like doesn't mean anything to most people. I've seen people complain that maybe the app is reviewed by whoever maintains the remote that it's from, so it's not necessarily true to say it hasn't been reviewed. But something indicating that it's there because of Sideload I dunno. Opening for discussion :)

Screenshot from 2021-09-15 14 01 15

### CODE REVIEW

**Comment by cassidyjames** [comment]
I am leaning toward the "Non-Curated" since that's the language we use elsewhere; otherwise I would want to change all of that language at the same time. And I think dropping the first sentence would be enough to make it not wordy but convey the same implications; I think trying to explain where it _did_ come from is probably outside the scope of this badge?

**Comment by cassidyjames** [comment]
Also as a random thought, I'd probably stick this one first because it also affects the following data; if we didn't curate it, we can't guarantee the rest of that data, either—so it's the most important badge.

**Comment by danrabbit** [comment]
@cassidyjames pushed

**Review by cassidyjames — COMMENTED** [review]
Dope

**Review by cassidyjames — APPROVED** [review]

**Pull request merged**
