### PR TITLE
Show an error when updating cache failed

### PR DESCRIPTION
**Pull request by donadigo**
**Depends on a new release of Granite.**

Shows an error info bar with "Try Again" button when updating the cache fails for some reason.

### CODE REVIEW

**Comment by danrabbit** [comment]
Wouldn't this error mean no package operations can be taken until it gets resolved? An info bar seems kind of passive for an error of this magnitude.

**Comment by donadigo** [comment]
@danrabbit no, since the user will still be able to see installed apps in some cases.

**Comment by donadigo** [comment]
The branch is now ready to review.

**Comment by danrabbit** [comment]
screenshot from 2017-10-25 13 06 30

With this much text, I think this should be a dialog.

**Comment by snwh** [comment]
definitely too verbose for an infobar

**Comment by cassidyjames** [comment]
I feel like this is pretty heavy, technical information to be showing to the user by default, as well. I'd be okay with an error infobar if it was:

>Failed to fetch updates. [Details] [Try Again]

or something

**Comment by donadigo** [comment]
@cassidyjames @danrabbit done.

**Pull request merged**
