### PR TITLE
Sort installed drivers with up to date apps

### LINKED ISSUE #251: Sort installed drivers with "up to date" apps
> Only odd thing is now that is kind of "pinned" to the top of the installed tab, but :shrug:

&mdash;@cassidyjames

I agree it's kind of odd.

### PR DESCRIPTION
**Pull request by zeebok**
Fixes #251 
I needed to add a new interface for detecting if the current row being looked at in the list is installed. This is so installed drivers are sorted with everything else, but new drivers yet to be installed show up in a header  called "Available Drivers" which use just be "Drivers".

### CODE REVIEW

**Comment by zeebok** [comment]
If you'd like I can look into refreshing the list view.

**Comment by donadigo** [comment]
@zeebok sorry for the late response. I would like to get the sorting issue resolved first, if you want to look at it, go ahead. If not I can look at this PR again and review it without taking the issue into account.

**Comment by zeebok** [comment]
I *am* working on this if you are wondering. The merge is done but the behavior seems to have broken in parts. Free time is a little harder to find lately but I am still trying to put time into fixing it.

**Comment by danrabbit** [comment]
Gonna close this since it needs fixing and conflicts with master. Feel free to reopen if that changes :)

**Pull request closed without merging**
