### PR TITLE
AppInfoView.vala: Add share button to footer

### LINKED ISSUE #190: Add "Copy Link" function
To easily share apps over the internets, copy the `appstream://` link to the clipboard

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #190 

Did this as "share" instead of link specifically in case we want to eventually make this a menu with more options like mail, twitter, etc

### CODE REVIEW

**Comment by cassidyjames** [comment]
I feel like this design is a regression since it requires tooltips to know for sure what each icon does. Was removing the labels intentional?
screenshot from 2017-06-23 13 05 55

**Comment by cassidyjames** [comment]
Master for reference
screenshot from 2017-06-23 13 06 44

**Comment by cassidyjames** [comment]
Can confirm that functionality-wise this seems good.

**Comment by danrabbit** [comment]
Yeah I killed the labels because it makes each button a different width or if you make them homogeneous it makes the spacing look all fucky for the icons. How about like this instead?

screenshot from 2017-06-23 12 27 51

**Pull request merged**
