### PR TITLE
AppInfoView: Always show origin as label

### LINKED ISSUE #233: Expose non-curated app remote
I've heard from a couple folks that they want a way to know which apps were made for elementary OS. While we still have apps from the Ubuntu repos, perhaps we need a way to mark those apps so that people know that they are not from our repos.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44000145-mark-apps-from-the-ubuntu-repos?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #233 

## AppCenter app

Screenshot from 2020-01-23 21 27 34@2x

## elementary app

Screenshot from 2020-01-23 21 27 57@2x

## Ubuntu repo app

Screenshot from 2020-01-23 21 28 06@2x

## App with multiple origins

Screenshot from 2020-01-23 21 28 22@2x

### CODE REVIEW

**Comment by cassidyjames** [comment]
One issue I noticed:

Screenshot from 2020-01-24 10 31 07@2x

**Comment by danrabbit** [comment]
I don't really like showing this label for AppCenter and elementary updates repos. This seems weird like exposing the way the sausage is made for no real purpose.

I do think it makes sense to remind users of non-curated and third party repos, but I'm not certain there's enough context here that the string really indicates its purpose on its own. In the context of the combobox I think it's clearer that you are choosing where to download from but on it's own I don't know that it conveys that information.

I'm also not a fan of this layout, especially when they actually are multiple sources. This seems really messy to me compared to the current layout. If you feel the layout of the origin information should change, I think it makes more sense to put it closer to the download information.

**Comment by danrabbit** [comment]
14E2FB0D-5239-4806-AE92-5C5EAD00EBDE
6F5CCC36-CB4E-472F-A7C5-E48A40FB6AD2

**Comment by cassidyjames** [comment]
Closing (for now) in favor of discussions we've had in Slack and I've tried to sum up on #233

**Pull request closed without merging**
