### PR TITLE
Styles: Add fallbacks for downstreams

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes https://github.com/pop-os/shop/issues/215. Does not affect or override styles on elementary OS.

### CODE REVIEW

**Comment by danrabbit** [comment]
Can we add these to the widgets they effect instead of to the whole screen?

**Comment by cassidyjames** [comment]
@danrabbit sure, though I think we use palette colors for the update badge, default application header background, and categories. Does adding it for the whole screen hurt anything in this case, or would it be better to add it three times?

**Comment by danrabbit** [comment]
My understanding is that this pulls in the provider for the construction of all style contexts, even ones that don't use it. So I think it's less efficient, especially as we have more widgets on screen. I could be wrong about this though and maybe it's negligible

**Comment by danrabbit** [comment]
Poked someone about it and they said probably not a significant performance impact

**Review by danrabbit — APPROVED** [review]
I can confirm that this resolves issues when using Adwaita and I don't see any impact in Greenfield

**Pull request merged**
