### PR TITLE
Use libhandy for screenshots

### PR DESCRIPTION
**Pull request by fs3o5**
Adds #1142 and switches dependency libhandy to libhandy-1

### CODE REVIEW

**Review by cassidyjames — CHANGES_REQUESTED** [review]
Yay, swiping on the trackpad feels so much better, here! But it looks like some things were lost in the port to LibHandy.

- [x] Indicator dots are not visible (could require in-app styles or stylesheet work)
- [ ] Buttons should show as insensitive when you can't go back/forward

That's what I noticed so far at a glance.

**Comment by fs3o5** [comment]
The buttons should now become insensitive.
I'm not sure what's happening on the dots. For me they become visible as soon as I open any other app.

**Comment by danrabbit** [comment]
I think whatever is causing the same issue with header text color is also affecting the dots here. So I would say it's not an issue with this branch

**Review by cassidyjames — APPROVED** [review]
UX-wise this is good to go! @danrabbit were you happy with the code?

**Pull request merged**
