### PR TITLE
Escape XML characters in OS description

### LINKED ISSUE #532: Operating System Updates showing html tags
image

### PR DESCRIPTION
**Pull request by donadigo**
Fix #532.

Escapes XML characters out of the package name, summary and the version so that we don't have errors while parsing those by the XML parser.

### CODE REVIEW

**Comment by tintou** [comment]
Better use this to escape things : https://valadoc.org/glib-2.0/GLib.Markup.escape_text.html

**Comment by donadigo** [comment]
@tintou fixed.

**Comment by tintou** [comment]
In this context, GLib.Markup.printf_escaped is even better

**Comment by donadigo** [comment]
@tintou done, thanks for the suggestion.

**Pull request merged**
