### PR TITLE
Show Uninstall button in Updates view

### LINKED ISSUE #632: Show uninstall button on updates page
Splitting out from #548. It might be useful to show an Uninstall button for apps on the updates/installed page.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/55722711-show-uninstall-button-on-updates-page?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57667267&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by isantop**
This PR adds uninstall buttons to the Updates view. They appear to be fully functional and work great without any additional changes. 

Fixes #632

### CODE REVIEW

**Comment by isantop** [comment]
Poking @cassidyjames for good measure

**Comment by cassidyjames** [comment]
Poking @danrabbit for better measure

**Comment by cassidyjames** [comment]
Talked to @danrabbit in Slack. Similar to #634, we want to only show the button in certain contexts; having two buttons in the row is weird, so if it's an update, we don't want an uninstall button. Apps under the "Up to Date" section should have the single Uninstall button, though.

**Comment by jeremypw** [comment]
I am closing this as there has been no action for 10 months and an alternative branch exists.

**Pull request closed without merging**
