### PR TITLE
Fix the dock icon badge count

### LINKED ISSUE #1136: AppCenter updates count always showing zero (0) on plank.
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
AppCenter updates counts always showing zero (0) on plank.

### Expected behavior
In the example below, plank should show 1 update on the AppCenter icon.

### Screenshots or screen recordings

2019-11-15 13-27-15 ekran görüntüsü

2019-11-16 17-52-49 ekran görüntüsü

## Platform Information
 - OS: elementary OS
 - OS Version: Juno
 - Hardware info: Thinkpad T430

- [X] I'm using the latest released stable version

## Additional context
```console
appcenter:	3.2.0+r2067+pkg81~ubuntu5.0.1
plank:	        0.11.4+git20190318.fb624c21-0elementary5.0.1
```

### LINKED ISSUE #1172: The indicator of available updates is broken
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The notifications of available updates is broken.

### To Reproduce
Wait for available updates and the AppCenter icon to show up in Plank.

### Expected behavior
The number of updates available should be the same (and correct).

### Screenshots or screen recordings
Captura de pantalla de 2020-01-10 08-53-26
Shows `0` updates. This is wrong in itself, but also wrong because there are indeed updates.

Captura de pantalla de 2020-01-10 08-53-35
No indication of available updates in the `Installed`button.

Captura de pantalla de 2020-01-10 08-53-42
There are indeed a number of available updates.

## Platform Information
Captura de pantalla de 2020-01-10 09-01-30

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Related to #874, but more broken.

### PR DESCRIPTION
**Pull request by getsnoopy**
Previously, the dock icon badge would always show that there are
0 updates even though the badge would only be shown when there are
updates. This commit fixes this issue by updating the badge label
after the badge has been displayed, which seems to work.

Fixes #1172
Fixes #1136

### CODE REVIEW

**Comment by vjr** [comment]
Any review comments for this PR on whether it can be merged to master?

**Comment by danrabbit** [comment]
OP, can you please update this branch to master and/or allow commits from repo admins?

**Comment by getsnoopy** [comment]
@danrabbit Done.

**Comment by alpancs** [comment]
Hi guys, any updates to this PR?

**Comment by cassidyjames** [comment]
@getsnoopy we still can't update this branch. :confused: Could you update from master and/or give permissions for us to do so?

**Comment by getsnoopy** [comment]
@cassidyjames Done

**Comment by cassidyjames** [comment]
@davidmhewitt provided this feedback in Slack:

>Calling those things in either order should work. But I've never experienced that issue. I guess there's no harm in merging it if it claims to fix the issue, but I'd be more interested in the actual cause.

**Comment by getsnoopy** [comment]
It might be a race condition, but I don't know exactly why it's an issue. Either way, it seems to fix it for me. Let's merge this in.

**Comment by getsnoopy** [comment]
Could someone please merge this in if there are no other issues with it? The PR has been open for quite a while now.

**Comment by danrabbit** [comment]
It seems like David has a competing branch here: https://github.com/elementary/appcenter/pull/1298

I'm inclined to close this branch since that should be the proper fix.

**Pull request closed without merging**
